import 'package:cardmaker/app/features/editor/controller.dart';
import 'package:cardmaker/core/values/app_colors.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class StickerPanel extends StatelessWidget {
  final CanvasController controller;

  const StickerPanel({super.key, required this.controller});

  @override
  Widget build(BuildContext context) {
    final categories = {
      'Popular': [
        '😍',
        '🥳',
        '💝',
        '🌈',
        '💎',
        '👑',
        '😎',
        '🎀',
        '🥰',
        '🙌',
        '💯',
        '🚀',
        '🎯',
        '🏆',
        '🎖️',
        '🥇',
        '🎗️',
        '😻',
        '🤩',
        '🔥',
      ],
      'Emojis': [
        '😀',
        '😂',
        '😘',
        '🙂',
        '😊',
        '😇',
        '🤗',
        '🤔',
        '😋',
        '😜',
        '🤪',
        '😴',
        '🥺',
        '😢',
        '😉',
        '🤓',
        '😣',
        '😝',
        '😗',
        '😙',
      ],
      'Hearts': [
        '❤️',
        '🧡',
        '💛',
        '💚',
        '💙',
        '💜',
        '🖤',
        '🤍',
        '🤎',
        '💕',
        '💞',
        '💓',
        '💗',
        '💖',
        '💘',
        '💟',
        '❣️',
        '💌',
        '💑',
        '💋',
      ],
      'Party': [
        '🎉',
        '🎊',
        '🎈',
        '🎁',
        '🎂',
        '🍰',
        '🪅',
        '🎆',
        '🎇',
        '🍾',
        '🥂',
        '🎤',
        '🕺',
        '💃',
        '🎸',
        '🥁',
        '🎺',
        '🎻',
        '🎵',
        '🎶',
      ],
      'Birthdays': [
        '🧁',
        '🕯️',
        '🎠',
        '🎡',
        '🎈',
        '🎁',
        '🎂',
        '🥳',
        '🎊',
        '🎉',
        '🎀',
        '🥂',
        '🎶',
        '🧁',
        '🕯️',
        '🎠',
        '🎡',
        '🎈',
        '🎁',
        '🎂',
      ],
      'Weddings': [
        '💍',
        '👰',
        '🤵',
        '💒',
        '💐',
        '👰‍♀️',
        '🤵‍♂️',
        '🎩',
        '🌸',
        '💏',
        '👩‍❤️‍👨',
        '👩‍❤️‍👩',
        '👨‍❤️‍👨',
        '💐',
        '💍',
        '💒',
        '👰',
        '🤵',
        '🎩',
        '🌸',
      ],
      'Holidays': [
        '🎄',
        '🎅',
        '🦌',
        '❄️',
        '☃️',
        '🎃',
        '👻',
        '🦃',
        '🐰',
        '🥚',
        '🇺🇳',
        '🕎',
        '🎍',
        '🎑',
        '🪔',
        '🎆',
        '🎇',
        '🎁',
        '🧧',
        '🎄',
      ],
      'Leaves': [
        '🍃',
        '🌿',
        '🍂',
        '🍁',
        '🌱',
        '🌾',
        '🍃',
        '🌿',
        '🍂',
        '🍁',
        '🌱',
        '🌾',
        '🍃',
        '🌿',
        '🍂',
        '🍁',
        '🌱',
        '🌾',
        '🍃',
        '🌿',
      ],
      'Alphabet': [
        '🇦',
        '🇧',
        '🇨',
        '🇩',
        '🇪',
        '🇫',
        '🇬',
        '🇭',
        '🇮',
        '🇯',
        '🇰',
        '🇱',
        '🇲',
        '🇳',
        '🇴',
        '🇵',
        '🇶',
        '🇷',
        '🇸',
        '🇹',
      ],
      'Nature': [
        '🌺',
        '🌻',
        '🌷',
        '🌹',
        '🌳',
        '🌲',
        '🌴',
        '🌵',
        '🌊',
        '⛅',
        '☀️',
        '🌙',
        '🌍',
        '🌬️',
        '🌪️',
        '🌼',
        '🌸',
        '🌻',
        '🌷',
        '🌹',
      ],
      'Animals': [
        '🐶',
        '🐱',
        '🐻',
        '🐼',
        '🐨',
        '🦁',
        '🐯',
        '🦒',
        '🦊',
        '🦄',
        '🐘',
        '🦋',
        '🐝',
        '🦉',
        '🐦',
        '🐳',
        '🐬',
        '🦚',
        '🐢',
        '🐙',
      ],
      'Food': [
        '🍎',
        '🍇',
        '🍓',
        '🍒',
        '🍉',
        '🍍',
        '🍔',
        '🍕',
        '🍟',
        '🍣',
        '🍦',
        '🍩',
        '☕',
        '🍵',
        '🥐',
        '🥞',
        '🍜',
        '🥗',
        '🍪',
        '🍫',
      ],
      'Travel': [
        '✈️',
        '🗺️',
        '🏖️',
        '🏝️',
        '⛰️',
        '🏕️',
        '🗽',
        '🗼',
        '🏰',
        '🗻',
        '🚗',
        '🚂',
        '⛵',
        '🛳️',
        '🛸',
        '🎒',
        '🧳',
        '🛫',
        '🛬',
        '🗿',
      ],
      'Motivational': [
        '💪',
        '💡',
        '✨',
        '👊',
        '🌱',
        '💫',
        '🧠',
        '🏅',
        '🌟',
        '🎯',
        '💯',
        '⚡',
        '🌍',
        '🚀',
        '🏆',
        '🎖️',
        '🥇',
        '🙌',
        '🌈',
        '🔥',
      ],
      'Social Media': [
        '📸',
        '📷',
        '📱',
        '💬',
        '🗣️',
        '🔗',
        '📍',
        '🖼️',
        '🎥',
        '🎬',
        '🔄',
        '🔃',
        '👍',
        '👀',
        '📩',
        '📤',
        '🌐',
        '📲',
        '🔔',
        '📧',
      ],
      'Symbols': [
        '⭐',
        '⚡',
        '💥',
        '🎪',
        '⚙️',
        '🛠️',
        '🔮',
        '🔒',
        '🔑',
        '🛡️',
        '💣',
        '🎰',
        '🧩',
        '🎨',
        '🖌️',
        '🖍️',
        '✂️',
        '📏',
        '📐',
        '🧬',
      ],
      'Events': [
        '🎫',
        '🎭',
        '🎤',
        '🎥',
        '🎡',
        '🎢',
        '🎠',
        '🎟️',
        '🏟️',
        '🎲',
        '🎿',
        '🏇',
        '🏀',
        '⚽',
        '🏈',
        '🎾',
        '🏓',
        '🏒',
        '⛳',
        '🏸',
      ],
      'Baby': [
        '👶',
        '🍼',
        '🧸',
        '🚼',
        '👼',
        '🛁',
        '👶',
        '🍼',
        '🧸',
        '🚼',
        '👼',
        '🛁',
        '👶',
        '🍼',
        '🧸',
        '🚼',
        '👼',
        '🛁',
        '👶',
        '🍼',
      ],
      'Fitness': [
        '🏋️',
        '🤸',
        '🏃',
        '🚴',
        '🏊',
        '🧘',
        '🥊',
        '🏋️‍♀️',
        '🏋️‍♂️',
        '🤸‍♀️',
        '🤸‍♂️',
        '🏃‍♀️',
        '🏃‍♂️',
        '🚴‍♀️',
        '🚴‍♂️',
        '🏊‍♀️',
        '🏊‍♂️',
        '🧘‍♀️',
        '🧘‍♂️',
        '🥊',
      ],
      'Daily Used': [
        '📱',
        '📧',
        '📲',
        '💬',
        '📞',
        '📅',
        '⏰',
        '🕒',
        '📍',
        '📝',
        '✉️',
        '📩',
        '📤',
        '📥',
        '🖱️',
        '💻',
        '🖨️',
        '📋',
        '📊',
        '📈',
      ],
    };

    return Container(
      height: 180,
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Get.theme.shadowColor.withOpacity(0.1),
            blurRadius: 4,
            offset: Offset(0, -3),
          ),
        ],
        // borderRadius: BorderRadius.vertical(top: Radius.circular(25)),
        color: Get.theme.colorScheme.surfaceContainerHighest,
      ),
      child: DefaultTabController(
        length: categories.length,
        child: Column(
          children: [
            Container(
              height: 33,
              padding: EdgeInsets.symmetric(horizontal: 0),
              decoration: BoxDecoration(
                color: Get.theme.colorScheme.surfaceContainer,
                // borderRadius: BorderRadius.circular(25),
              ),
              child: TabBar(
                isScrollable: true,
                dividerHeight: 0,
                tabAlignment: TabAlignment.start,
                indicatorSize: TabBarIndicatorSize.tab,
                indicatorColor: Colors.transparent,
                indicator: BoxDecoration(
                  borderRadius: BorderRadius.circular(25),
                  // color: AppColors.branding.withOpacity(0.1),
                ),
                labelColor: AppColors.branding,
                indicatorWeight: 3,
                labelStyle: TextStyle(
                  fontWeight: FontWeight.w600,
                  fontSize: 14,
                ),
                unselectedLabelStyle: TextStyle(
                  fontWeight: FontWeight.w500,
                  fontSize: 14,
                ),
                tabs: categories.keys.map((category) {
                  return Tab(text: category);
                }).toList(),
              ),
            ),
            Expanded(
              child: TabBarView(
                children: categories.values.map((stickers) {
                  return SingleChildScrollView(
                    padding: EdgeInsets.all(16),
                    child: Wrap(
                      spacing: 8, // Horizontal spacing between stickers
                      runSpacing: 8, // Vertical spacing between rows
                      alignment:
                          WrapAlignment.start, // Align stickers to the start
                      children: stickers.asMap().entries.map((entry) {
                        final index = entry.key;
                        final sticker = entry.value;
                        return GestureDetector(
                          onTap: () {
                            controller.addSticker(sticker);
                            // Haptic feedback
                            // HapticFeedback.lightImpact();
                          },
                          child: AnimatedContainer(
                            duration: Duration(milliseconds: 150),
                            width: 48, // Fixed width for each sticker
                            height: 48, // Fixed height for each sticker
                            decoration: BoxDecoration(
                              color: Colors.grey.shade50,
                              borderRadius: BorderRadius.circular(12),
                              border: Border.all(color: Colors.grey.shade200),
                            ),
                            child: Center(
                              child: Text(
                                sticker,
                                style: TextStyle(fontSize: 28),
                              ),
                            ),
                          ),
                        );
                      }).toList(),
                    ),
                  );
                }).toList(),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
