// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCk3Pc32ptEtfgDWTT9Is4x8ym4q-mJTo',
    appId: '1:370527194012:web:9943ec48c689af2dda1659',
    messagingSenderId: '370527194012',
    projectId: 'inkkaro-33115',
    authDomain: 'inkkaro-33115.firebaseapp.com',
    storageBucket: 'inkkaro-33115.firebasestorage.app',
    measurementId: 'G-4SJ1668LTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe2PEwNI6MfZqL-sErRkJ5EfGzoc_TPag',
    appId: '1:370527194012:android:8f56289e48f924ccda1659',
    messagingSenderId: '370527194012',
    projectId: 'inkkaro-33115',
    storageBucket: 'inkkaro-33115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtLA0Wn8h25whIOu81tkP7e09QKF9PTss',
    appId: '1:370527194012:ios:22ba94eeba304670da1659',
    messagingSenderId: '370527194012',
    projectId: 'inkkaro-33115',
    storageBucket: 'inkkaro-33115.firebasestorage.app',
    iosBundleId: 'com.example.cardmaker',
  );
}
