const stylishGoogleFonts = [
  'Playfair Display',
  'Lobster',
  'Pacifico',
  'Dancing Script',
  'Great Vibes',
  'Abril Fatface',
  'Merriweather',
  'Bebas Neue',
  'Poppins',
  'Josefin Sans',
  'Cormorant Garamond',
  'Cinzel',
  'Raleway',
  'Alfa Slab One',
  'Fjalla One',
  'Amatic SC',
  'Satisfy',
  'Sacramento',
  'Tangerine',
  'Prata',
  'Cookie',
  'Caveat',
  'Architects Daughter',
  'Kaushan Script',
  'Roboto Slab',
];
